install.packages("psych")
library(psych)
install.packages("car")
library(car)
getwd()
setwd('C:/Users/Admin/Desktop/Folders/EDUCTION/course material/MATPMD1/Project')
library(readxl)
Investment_Data <- read_excel("C:/Users/Admin/Desktop/Investment Data.xlsx")
View(Investment_Data)
investment<- Investment_Data
str(investment)
clean<-na.omit(investment)
str(clean)
summary(clean)
boxplot(clean$`Share Price (p)`)
cor(clean)
fitAll<-lm(`Share Price (p)`~ . ,data=clean)
fitAllf<-lm(`Share Price (p)`~ 1 ,data=clean)
forward<-step(fitAllf,direction = 'forward',scope =formula(fitAll) )
formula(forward)
best1<-lm(`Share Price (p)`~Dividend + Yield ,data=clean[-c(40,48),])
summary(best1)
hist(best1)
plot(backward)
fitAllB<-lm(`Share Price (p)`~ . ,data=clean[-c(40,48,49),])
backward1<-step(fitAllB,direction = 'backward')
bestbackward<-lm(`Share Price (p)` ~ `EPS(Current)` + `P/E` + MktCap + Dividend + 
               Yield + Beta ,data=clean[-c(40,48,49),])
plot(bestbackward)
hist(bestbackward$residuals)
Backward<- predict(bestbackward,newdata=clean,type='response')
clean$backward<-Backward
forward<- predict(best1,newdata=clean,type='response')
clean$forward<-forward
write.table(clean,file = 'investment1.csv',sep = ',')
