getwd()

setwd('C:/Users/Admin/Desktop/Folders/EDUCTION/course material/MATPMD1/Project')
investment<- Investment_Data
str(investment)
colnames(investment)
install.packages("psych")
library(psych)
install.packages("car")
library(car)
sum(is.na(investment))
clean1<-na.omit(investment)
write.table(clean1,sep = ',')
write.table(clean1,file = 'investment1.csv',row.names = F,sep = ',')
summary(clean1)
plot(clean1$`Share Price (p)`,clean1$Employees)
fit<- lm(`Share Price (p)`~.,data=clean1)
summary(fit)
fit1<- lm(`Share Price (p)`~MktCap+`Avg Vol`+`P/E`+`EPS(Current)`+ Dividend + Yield + Alpha + Beta + Employees + `EPS(2016)`+`EPS(2017)`+ `Net Revenue(2016)` + `Net Profit(2016)`+`Net Profit(2017)` ,data=clean1)
summary(fit1)
fit2<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Alpha + Beta + Employees + `EPS(2016)`+`EPS(2017)`+ `Net Revenue(2016)` + `Net Profit(2016)`+`Net Profit(2017)` ,data=clean1)
summary(fit2)
fit3<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Alpha + Beta + Employees + `EPS(2016)`+`EPS(2017)`+ `Net Profit(2016)`+`Net Profit(2017)` ,data=clean1)
summary(fit3)
fit4<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Alpha + Beta + Employees + `EPS(2016)`+`EPS(2017)`+ `Net Profit(2016)` ,data=clean1)
summary(fit4)
fit5<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Alpha + Beta + `EPS(2016)`+`EPS(2017)`+ `Net Profit(2016)` ,data=clean1)
summary(fit5)
fit6<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Alpha + Beta +`EPS(2017)`+ `Net Profit(2016)` ,data=clean1)
summary(fit6)
fit7<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Beta +`EPS(2017)`+ `Net Profit(2016)` ,data=clean1)
summary(fit7)
fit8<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield + Beta + `Net Profit(2016)` ,data=clean1)
summary(fit8)
fit9<- lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield  + `Net Profit(2016)` ,data=clean1)
summary(fit9)
fit10<-lm(`Share Price (p)`~MktCap+`P/E`+`EPS(Current)`+ Dividend + Yield ,data=clean1)
summary(fit10)
fit11<- lm(`Share Price (p)`~`P/E`+`EPS(Current)`+ Dividend + Yield ,data=clean1)
summary(fit11)
fit12<- lm(`Share Price (p)`~`EPS(Current)`+ Dividend + Yield ,data=clean1)
summary(fit12)
fit13<- lm(`Share Price (p)`~Dividend + Yield ,data=clean1)
summary(fit13)
fitall<- lm(`Share Price (p)`~.,data=clean1)
step(fit13,direction = 'backward', scope=formula(fitall))
vif()
crPlots(fit13)
plot(fit12$residuals)
qqnorm(fit12$residuals)
qqline(fit12$residuals)
plot(fit13)
res<-fit13$residuals
res$ouliers
install.packages("leaps")
library(leaps)
hi<-regsubsets(`Share Price (p)`~.,data=clean1,nvmax =8)
hi2<-summary(hi)
data.frame(Adj.R2=which.max(hi2$adjr2))
summary(fit13)

influencePlot(fit13)
fit14<- lm(`Share Price (p)`~ Dividend + Yield ,data=clean1[-c(48,40),])
vif(fit14)
plot(fit14)
summary(fit14)
cor.plot(clean1)
cor(clean1)
cortest.mat(clean1)
predictshare<- predict(fit13,newdata=clean1,type='response')
clean1$predictshareprice<-predictshare
View(clean1)
vif(fit14)
eco<-
